breadcrumb_separator: /
fixed_header: true
display_fixed_site_name: true
scrolltop_display: true
three_columns_grid_layout: grid_3_6_3
offset_fullwidth_content: true
content_background_color: gray
color_scheme: default
reading_time: true
share_links: true
print_button: true
font_resize: true
post_progress: true
affix_side: true
headings_font_family: hff-08
paragraph_font_family: pff-05
sitename_font_family: sff-10
slogan_font_family: slff-08
slideshow_effect: fade
slideshow_effect_time: '10'
internal_banner_effect: slide
breaking_effect: fade
breaking_effect_time: '5'
_core:
  default_config_hash: vecybga0cS04jorLiUd8Dcw6ZeMxt_Qtwr7KRI3orQ0
langcode: ru
